### ISSUE TITLE
SizeLimitExceededError: Size Limit Exceeded with profile

### ISSUE THREAD

**Issue by ravusandeep** [typ90/meteor-accounts-ldap#31]

**Comment by ravusandeep** [comment]
same as this https://github.com/etyp/meteor-accounts-ldap/issues/18

**Comment by ravusandeep** [comment]
Your app is crashing. Here's the latest log:
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
=> Meteor server restarted

events.js:141
      throw er; // Unhandled 'error' event
      ^
SizeLimitExceededError: Size Limit Exceeded
    at messageCallback (C:\Users\sravu\AppData\Local\.meteor\packages\typ_ldapjs\0.7.3\npm\node_modules\ldapjs\lib\client\client.js:867:40)
    at Parser.onMessage (C:\Users\sravu\AppData\Local\.meteor\packages\typ_ldapjs\0.7.3\npm\node_modules\ldapjs\lib\client\client.js:199:12)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.write (C:\Users\sravu\AppData\Local\.meteor\packages\typ_ldapjs\0.7.3\npm\node_modules\ldapjs\lib\messages\parser.js:105:8)
    at end (C:\Users\sravu\AppData\Local\.meteor\packages\typ_ldapjs\0.7.3\npm\node_modules\ldapjs\lib\messages\parser.js:71:19)
    at Parser.write (C:\Users\sravu\AppData\Local\.meteor\packages\typ_ldapjs\0.7.3\npm\node_modules\ldapjs\lib\messages\parser.js:107:10)
    at Socket.onData (C:\Users\sravu\AppData\Local\.meteor\packages\typ_ldapjs\0.7.3\npm\node_modules\ldapjs\lib\client\client.js:155:24)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
Exited with code: 1
Your application is crashing. Waiting for file change.
