### ISSUE TITLE
 Adding typ:accounts-ldap package Failed at the dtrace-provider@0.2.8 install script

### ISSUE THREAD

**Issue by jeganfernando** [typ90/meteor-accounts-ldap#32]
C:\ldaptest>meteor add typ:accounts-ldap
 => Errors while adding packages:

While loading package typ:ldapjs@0.7.3:
error: Command failed:
C:\Users\fernjega\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\b
in\npm.cmd
rebuild --update-binary
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with
exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\fernjega\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\
lib\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command
"C:\\Users\\fernjega\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.5.0\\mt-os.windows.x86_32\\d
ev_bundle\\bin\\node.exe"
"C:\\Users\\fernjega\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.5.0\\mt-os.windows.x86_32\\d
ev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd
C:\Users\fernjega\AppData\Local\.meteor\packages\typ_ldapjs\0.7.3\npm\node_modules\.temp-1ribbh7\nod
e_modules\ldapjs\node_modules\dtrace-provider
gyp ERR! node -v v4.8.3
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dtrace-provider@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.2.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output
above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\fernjega\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\.
npm\_logs\2017-06-01T15_18_03_237Z-debug.log
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with
exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\fernjega\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\
lib\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command
"C:\\Users\\fernjega\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.5.0\\mt-os.windows.x86_32\\d
ev_bundle\\bin\\node.exe"
"C:\\Users\\fernjega\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.5.0\\mt-os.windows.x86_32\\d
ev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd
C:\Users\fernjega\AppData\Local\.meteor\packages\typ_ldapjs\0.7.3\npm\node_modules\.temp-1ribbh7\nod
e_modules\ldapjs\node_modules\dtrace-provider
gyp ERR! node -v v4.8.3
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dtrace-provider@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.2.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output
above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\fernjega\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\.
npm\_logs\2017-06-01T15_18_03_237Z-debug.log

**Comment by cknts** [comment]
one of these things helped me, i cannot exactly say what does the trick

- try what error messages says -> "node-gyp rebuild"
- run in powershell -> https://www.npmjs.com/package/windows-build-tools
- install ldapjs with "--no-optional"
