### ISSUE TITLE
While loading typ:ldapjs@0.7.3...: error: Command failed:

### ISSUE THREAD

**Issue by irom77** [typ90/meteor-accounts-ldap#34]
I have this 

```
meteor add typ:accounts-ldap
 => Errors while adding packages:

While loading typ:ldapjs@0.7.3...:
error: Command failed:
/Users/irekromaniuk/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --update-binary
usdt.c:212:9: warning: implicit declaration of function 'usdt_dof_section_free' is invalid in C99
[-Wimplicit-function-declaration]
usdt_dof_section_free(&strtab);
^
usdt.c:238:9: warning: implicit declaration of function 'usdt_dof_file_free' is invalid in C99
[-Wimplicit-function-declaration]
usdt_dof_file_free(provider->file);
^
2 warnings generated.
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:69:44: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> New(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:70:45: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> Fire(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:87:44: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> New(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:88:49: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> AddProbe(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:89:52: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> RemoveProbe(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:90:47: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> Enable(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:91:48: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> Disable(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:92:45: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> Fire(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
../dtrace_provider.cc:23:17: error: calling a protected constructor of class 'v8::HandleScope'
HandleScope scope;
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:885:13: note: declared protected here
V8_INLINE HandleScope() {}
^
../dtrace_provider.cc:25:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an
lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)' (aka 'v8::Local<v8::Value>
(const v8::internal::Arguments &)')
Local<FunctionTemplate> t =
FunctionTemplate::New(DTraceProvider::New);
^~~~~~~~~~~~~~~~~~~
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:4350:16: note: passing argument to parameter
'isolate' here
Isolate* isolate, FunctionCallback callback = 0,
^
../dtrace_provider.cc:26:58: error: 'New' is a private member of
'v8::PersistentBase<v8::FunctionTemplate>'
constructor_template =
Persistent<FunctionTemplate>::New(t);
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:639:23: note: declared private here
V8_INLINE static T* New(Isolate* isolate, T* that);
^
../dtrace_provider.cc:26:28: error: too few arguments to function call, expected 2, have 1; did you
mean 'DTraceProbe::New'?
constructor_template = Persistent<FunctionTemplate>::New(t);
^~~~~~~~~~
DTraceProbe::New
../dtrace_provider.h:69:34: note: 'DTraceProbe::New' declared here
static v8::Handle<v8::Value> New(const v8::Arguments& args);
^
../dtrace_provider.cc:27:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not
a pointer; did you mean to use '.'?
constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
~~~~~~~~~~~~~~~~~~~~^~
.
../dtrace_provider.cc:27:27: error: no member named 'InstanceTemplate' in
'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not
a pointer; did you mean to use '.'?
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
~~~~~~~~~~~~~~~~~~~~^~
.
../dtrace_provider.cc:28:27: error: no member named 'SetClassName' in
'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:48: error: no member named 'NewSymbol' in 'v8::String'

constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
~~~~~~~~^
../dtrace_provider.cc:30:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to
'v8::Local<v8::FunctionTemplate>'
NODE_SET_PROTOTYPE_METHOD(constructor_template, "addProbe",
DTraceProvider::AddProbe);
^~~~~~~~~~~~~~~~~~~~
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:210:7: note: candidate constructor (the
implicit copy constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>'
to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:210:7: note: candidate constructor (the
implicit move constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>'
to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:214:13: note: candidate template ignored:
could not match 'Local' against 'Persistent'
V8_INLINE Local(Local<S> that)
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:326:13: note: candidate template ignored:
could not match 'S *' against 'Persistent<v8::FunctionTemplate>'
V8_INLINE Local(S* that)
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/node.h:253:71: note: passing argument to parameter
'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate>
recv,
^
../dtrace_provider.cc:31:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to
'v8::Local<v8::FunctionTemplate>'
NODE_SET_PROTOTYPE_METHOD(constructor_template, "removeProbe",
DTraceProvider::RemoveProbe);
^~~~~~~~~~~~~~~~~~~~
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:210:7: note: candidate constructor (the
implicit copy constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>'
to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:210:7: note: candidate constructor (the
implicit move constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>'
to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:214:13: note: candidate template ignored:
could not match 'Local' against 'Persistent'
V8_INLINE Local(Local<S> that)
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:326:13: note: candidate template ignored:
could not match 'S *' against 'Persistent<v8::FunctionTemplate>'
V8_INLINE Local(S* that)
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/node.h:253:71: note: passing argument to parameter
'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate>
recv,
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/irekromaniuk/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command
"/Users/irekromaniuk/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/irekromaniuk/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/private/var/folders/xw/bq505pzn53q6s_1y4x4ppzp00000gn/T/mt-1hdsf58/npm/node_modules/ldapjs/node_modules/dtrace-provider
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dtrace-provider@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.2.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
/Users/irekromaniuk/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/.npm/_logs/2017-08-16T18_45_44_995Z-debug.log
usdt.c:212:9: warning: implicit declaration of function 'usdt_dof_section_free' is invalid in C99
[-Wimplicit-function-declaration]
usdt_dof_section_free(&strtab);
^
usdt.c:238:9: warning: implicit declaration of function 'usdt_dof_file_free' is invalid in C99
[-Wimplicit-function-declaration]
usdt_dof_file_free(provider->file);
^
2 warnings generated.
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:69:44: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> New(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:70:45: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> Fire(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:87:44: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> New(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:88:49: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> AddProbe(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:89:52: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> RemoveProbe(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:90:47: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> Enable(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:91:48: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> Disable(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:92:45: error: no type named 'Arguments' in namespace 'v8'; did you mean
'v8::internal::Arguments'?
static v8::Handle<v8::Value> Fire(const v8::Arguments&
args);
^~~~~~~~~~~~~
v8::internal::Arguments
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments'
declared here
class Arguments;
^
../dtrace_provider.cc:23:17: error: calling a protected constructor of class 'v8::HandleScope'
HandleScope scope;
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:885:13: note: declared protected here
V8_INLINE HandleScope() {}
^
../dtrace_provider.cc:25:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an
lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)' (aka 'v8::Local<v8::Value>
(const v8::internal::Arguments &)')
Local<FunctionTemplate> t =
FunctionTemplate::New(DTraceProvider::New);
^~~~~~~~~~~~~~~~~~~
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:4350:16: note: passing argument to parameter
'isolate' here
Isolate* isolate, FunctionCallback callback = 0,
^
../dtrace_provider.cc:26:58: error: 'New' is a private member of
'v8::PersistentBase<v8::FunctionTemplate>'
constructor_template =
Persistent<FunctionTemplate>::New(t);
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:639:23: note: declared private here
V8_INLINE static T* New(Isolate* isolate, T* that);
^
../dtrace_provider.cc:26:28: error: too few arguments to function call, expected 2, have 1; did you
mean 'DTraceProbe::New'?
constructor_template = Persistent<FunctionTemplate>::New(t);
^~~~~~~~~~
DTraceProbe::New
../dtrace_provider.h:69:34: note: 'DTraceProbe::New' declared here
static v8::Handle<v8::Value> New(const v8::Arguments& args);
^
../dtrace_provider.cc:27:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not
a pointer; did you mean to use '.'?
constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
~~~~~~~~~~~~~~~~~~~~^~
.
../dtrace_provider.cc:27:27: error: no member named 'InstanceTemplate' in
'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not
a pointer; did you mean to use '.'?
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
~~~~~~~~~~~~~~~~~~~~^~
.
../dtrace_provider.cc:28:27: error: no member named 'SetClassName' in
'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:48: error: no member named 'NewSymbol' in 'v8::String'

constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
~~~~~~~~^
../dtrace_provider.cc:30:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to
'v8::Local<v8::FunctionTemplate>'
NODE_SET_PROTOTYPE_METHOD(constructor_template, "addProbe",
DTraceProvider::AddProbe);
^~~~~~~~~~~~~~~~~~~~
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:210:7: note: candidate constructor (the
implicit copy constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>'
to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:210:7: note: candidate constructor (the
implicit move constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>'
to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:214:13: note: candidate template ignored:
could not match 'Local' against 'Persistent'
V8_INLINE Local(Local<S> that)
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:326:13: note: candidate template ignored:
could not match 'S *' against 'Persistent<v8::FunctionTemplate>'
V8_INLINE Local(S* that)
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/node.h:253:71: note: passing argument to parameter
'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate>
recv,
^
../dtrace_provider.cc:31:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to
'v8::Local<v8::FunctionTemplate>'
NODE_SET_PROTOTYPE_METHOD(constructor_template, "removeProbe",
DTraceProvider::RemoveProbe);
^~~~~~~~~~~~~~~~~~~~
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:210:7: note: candidate constructor (the
implicit copy constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>'
to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:210:7: note: candidate constructor (the
implicit move constructor) not viable: no known conversion from 'Persistent<v8::FunctionTemplate>'
to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:214:13: note: candidate template ignored:
could not match 'Local' against 'Persistent'
V8_INLINE Local(Local<S> that)
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/v8.h:326:13: note: candidate template ignored:
could not match 'S *' against 'Persistent<v8::FunctionTemplate>'
V8_INLINE Local(S* that)
^
/Users/irekromaniuk/.node-gyp/4.8.4/include/node/node.h:253:71: note: passing argument to parameter
'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate>
recv,
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/irekromaniuk/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command
"/Users/irekromaniuk/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/irekromaniuk/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/private/var/folders/xw/bq505pzn53q6s_1y4x4ppzp00000gn/T/mt-1hdsf58/npm/node_modules/ldapjs/node_modules/dtrace-provider
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dtrace-provider@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.2.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
/Users/irekromaniuk/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/.npm/_logs/2017-08-16T18_45_44_995Z-debug.log
```

**Comment by pisacode** [comment]
hi did you find a solution?

**Comment by irom77** [comment]
Nope

**Comment by pisacode** [comment]
I have used this package and it is working just fine 

[https://github.com/JackAdams/meteor-accounts-ldap/](url)
