### ISSUE TITLE
difficulties to login on ldaps

### ISSUE THREAD

**Issue by FGDVLP** [typ90/meteor-accounts-ldap#38]
hi,

i got the errors : 

Exception while invoking method 'login' TypeError: **Cannot read property 'on' of undefined**
at setupSocket (/home/meteoruser/.meteor/packages/typ_ldapjs/.0.7.3.1brxoay.lw2j++os+web.browser+web.cordova/npm/node_modules/ldapjs/lib/client/client.js:111:15)

events.js:183
throw er; // Unhandled 'error' event
Error: **self signed certificate** in certificate chain
at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)

my certificate is official (not self-signed), 
if i set LDAP_DEFAULTS.ldapsCertificate to false, 
or if i set environment variable NODE_TLS_REJECT_UNAUTHORIZED to 0, 
then there is no "self signed certificate" error, 
but the "Cannot read property 'on' of undefined" error still remain.

**Comment by FGDVLP** [comment]
here the solution i found : 

1) add env var NODE_TLS_REJECT_UNAUTHORIZED=0 (despite it is an official one, not self-signed)

2) modify .meteor/packages/typ_ldapjs/.0.7.3.1brxoay.lw2j++os+web.browser+web.cordova/npm/node_modules/ldapjs/lib/client/client.js

  // var closeSocket = (opts.secure ? socket.socket : socket);
  if (socket.socket === undefined) { closeSocket = socket; }else{ closeSocket = socket.socket; }

any advice ?
